#!/usr/bin/perl -w

use strict;
use esmith::Build::CreateLinks qw(:all);

templates2events("/etc/ssh/sshd_config", qw(
   nethserver-base-save
   nethserver-openssh-update
));

safe_symlink("restart", "root/etc/e-smith/events/nethserver-openssh-update/services2adjust/sshd");



